@api @admin @Phase3
Feature: Role controller APIs

  Background:
    Given api testing is ready
    And the user uses token alias "admin"

  @smoke @regression
  Scenario: List roles returns role list
    When the user sends a GET request to "roles.list"
    Then the request should succeed
    And the response should match the "role-list" schema

  @regression
  Scenario: Create role with unique name succeeds
    Given value "newRoleName" is set to "AUTO_ROLE_${random.number:6}"
    And request body "createRolePayload" is defined as
      | key         | value                 |
      | name        | ${ctx.newRoleName}    |
      | description | Generated by API test |
    When the user sends a POST request to "roles.create" using request body "createRolePayload"
    Then the response status should be one of "200,201"
    And the response should match the "role-response" schema
    And store response field "id" as "newRoleId"

  @regression
  Scenario: Update and delete role by id succeeds
    Given value "flowRoleName" is set to "AUTO_ROLE_FLOW_${random.number:6}"
    And request body "flowRoleCreatePayload" is defined as
      | key         | value                |
      | name        | ${ctx.flowRoleName}  |
      | description | Flow role create     |
    When the user sends a POST request to "roles.create" using request body "flowRoleCreatePayload"
    Then the response status should be one of "200,201"
    And store response field "id" as "flowRoleId"
    And request body "flowRoleUpdatePayload" uses the "role-update-valid" payload
    When the user sends a PUT request to "roles.update" using request body "flowRoleUpdatePayload" with data
      | key     | value            |
      | path.id | ${ctx.flowRoleId} |
    Then the request should succeed
    When the user sends a DELETE request to "roles.delete" with data
      | key     | value            |
      | path.id | ${ctx.flowRoleId} |
    Then the response status should be one of "200,204"

  @regression
  Scenario: Get role by id returns role
    Given the "ADMIN" role id is stored as "adminRoleId"
    When the user sends a GET request to "roles.by-id" with data
      | key     | value             |
      | path.id | ${ctx.adminRoleId} |
    Then the request should succeed
    And the response should match the "role-response" schema

  @regression
  Scenario: Get role by name returns role
    When the user sends a GET request to "roles.by-name" with data
      | key       | value |
      | path.name | ADMIN |
    Then the request should succeed
    And the response should match the "role-response" schema

  @validation @negative @regression
  Scenario: Create role validation fails for blank name
    And request body "invalidRolePayload" uses the "role-create-invalid" payload
    When the user sends a POST request to "roles.create" using request body "invalidRolePayload"
    Then the response should indicate "bad request"
    And the response should match the "validation-error" schema
