package com.jaya.modal;

public enum NotificationType {
    BUDGET_EXCEEDED,
    BUDGET_WARNING,
    MONTHLY_SUMMARY,
    DAILY_REMINDER,
    WEEKLY_REPORT,
    UNUSUAL_SPENDING,
    RECURRING_EXPENSE,
    GOAL_ACHIEVEMENT,
    INACTIVITY_REMINDER,
    CUSTOM_ALERT,
    SUBSCRIPTION_RENEWAL,
    PAYMENT_DUE,
    EXPENSE_LIMIT_REACHED
}