import {
  Palette,
  Type,
  ALargeSmall,
  LayoutGrid,
  Sparkles,
  Contrast,
  Languages,
  CircleDollarSign,
  CalendarDays,
  Clock,
  Shield,
  Eye,
  ShieldCheck,
  Ban,
  Lock,
  Timer,
  Database,
  CloudUpload,
  HardDrive,
  Trash2,
  Brain,
  TrendingUp,
  CalendarClock,
  Bell,
  BarChart3,
  Accessibility,
  Keyboard,
  MonitorSmartphone,
  Focus,
  Minimize2,
  User,
  KeyRound,
  Download,
  AlertTriangle,
  RotateCcw,
  HelpCircle,
  MessageCircle,
  FileText,
  ShieldQuestion,
  Info,
} from "lucide-react";

export const LANGUAGE_OPTIONS = [
  { value: "en", labelKey: "settings.options.english" },
  { value: "hi", labelKey: "settings.options.hindi" },
  { value: "te", labelKey: "settings.options.telugu" },
];

export const CURRENCY_OPTIONS = [
  { value: "INR", label: "₹ INR", symbol: "₹" },
  { value: "USD", label: "$ USD", symbol: "$" },
  { value: "EUR", label: "€ EUR", symbol: "€" },
  { value: "GBP", label: "£ GBP", symbol: "£" },
  { value: "JPY", label: "¥ JPY", symbol: "¥" },
];

export const DATE_FORMAT_OPTIONS = [
  { value: "DD/MM/YYYY", label: "DD/MM/YYYY" },
  { value: "MM/DD/YYYY", label: "MM/DD/YYYY" },
  { value: "YYYY-MM-DD", label: "YYYY-MM-DD" },
  { value: "DD-MMM-YYYY", label: "DD-MMM-YYYY" },
];

export const FONT_SIZE_OPTIONS = [
  { value: "small", labelKey: "settings.options.small" },
  { value: "medium", labelKey: "settings.options.medium" },
  { value: "large", labelKey: "settings.options.large" },
  { value: "extra-large", labelKey: "settings.options.extraLarge" },
];

export const FONT_FAMILY_OPTIONS = [
  { value: "inter", label: "Inter" },
  { value: "poppins", label: "Poppins" },
  { value: "nunito", label: "Nunito" },
  { value: "roboto", label: "Roboto" },
  { value: "open-sans", label: "Open Sans" },
  { value: "lato", label: "Lato" },
  { value: "raleway", label: "Raleway" },
  { value: "montserrat", label: "Montserrat" },
  { value: "source-sans", label: "Source Sans 3" },
];

export const TIME_FORMAT_OPTIONS = [
  { value: "12h", labelKey: "settings.options.twelveHour" },
  { value: "24h", labelKey: "settings.options.twentyFourHour" },
];

export const BACKUP_FREQUENCY_OPTIONS = [
  { value: "daily", labelKey: "settings.options.daily" },
  { value: "weekly", labelKey: "settings.options.weekly" },
  { value: "monthly", labelKey: "settings.options.monthly" },
];

export const REPORT_SCHEDULE_OPTIONS = [
  { value: "none", labelKey: "settings.options.none" },
  { value: "weekly", labelKey: "settings.options.weekly" },
  { value: "monthly", labelKey: "settings.options.monthly" },
  { value: "quarterly", labelKey: "settings.options.quarterly" },
];

export const PROFILE_VISIBILITY_OPTIONS = [
  { value: "public", labelKey: "settings.options.public" },
  { value: "friends", labelKey: "settings.options.friendsOnly" },
  { value: "private", labelKey: "settings.options.private" },
];

export const APP_INFO = {
  version: "2.0.0",
  build: "mobile-20260319",
  lastUpdated: "2026-03-19",
};

export const SETTINGS_SECTIONS = [
  {
    id: "appearance",
    titleKey: "settings.sections.appearance",
    icon: Palette,
    items: [
      {
        id: "themeMode",
        type: "switch",
        labelKey: "settings.darkMode",
        descriptionKey: "settings.darkModeDesc",
        icon: Palette,
        stateKey: "themeMode",
        settingsKey: "themeMode",
        switchValueMapping: { on: "dark", off: "light" },
      },
      {
        id: "accentColor",
        type: "themePicker",
        labelKey: "settings.accentColor",
        descriptionKey: "settings.accentColorDesc",
        icon: Palette,
      },
      {
        id: "fontFamily",
        type: "select",
        labelKey: "settings.fontFamily",
        descriptionKey: "settings.fontFamilyDesc",
        icon: ALargeSmall,
        stateKey: "fontFamily",
        settingsKey: "fontFamily",
        options: FONT_FAMILY_OPTIONS,
      },
      {
        id: "fontSize",
        type: "select",
        labelKey: "settings.fontSize",
        descriptionKey: "settings.fontSizeDesc",
        icon: Type,
        stateKey: "fontSize",
        settingsKey: "fontSize",
        options: FONT_SIZE_OPTIONS,
      },
      {
        id: "compactMode",
        type: "switch",
        labelKey: "settings.compactMode",
        descriptionKey: "settings.compactModeDesc",
        icon: LayoutGrid,
        stateKey: "compactMode",
        settingsKey: "compactMode",
      },
      {
        id: "enableAnimations",
        type: "switch",
        labelKey: "settings.enableAnimations",
        descriptionKey: "settings.enableAnimationsDesc",
        icon: Sparkles,
        stateKey: "enableAnimations",
        settingsKey: "enableAnimations",
      },
      {
        id: "highContrastMode",
        type: "switch",
        labelKey: "settings.highContrastMode",
        descriptionKey: "settings.highContrastModeDesc",
        icon: Contrast,
        stateKey: "highContrastMode",
        settingsKey: "highContrastMode",
      },
    ],
  },
  {
    id: "preferences",
    titleKey: "settings.sections.preferences",
    icon: Languages,
    items: [
      {
        id: "language",
        type: "select",
        labelKey: "settings.language",
        descriptionKey: "settings.languageDesc",
        icon: Languages,
        stateKey: "language",
        settingsKey: "language",
        options: LANGUAGE_OPTIONS,
      },
      {
        id: "currency",
        type: "select",
        labelKey: "settings.defaultCurrency",
        descriptionKey: "settings.defaultCurrencyDesc",
        icon: CircleDollarSign,
        stateKey: "currency",
        settingsKey: "currency",
        options: CURRENCY_OPTIONS,
      },
      {
        id: "dateFormat",
        type: "select",
        labelKey: "settings.dateFormat",
        descriptionKey: "settings.dateFormatDesc",
        icon: CalendarDays,
        stateKey: "dateFormat",
        settingsKey: "dateFormat",
        options: DATE_FORMAT_OPTIONS,
      },
      {
        id: "timeFormat",
        type: "select",
        labelKey: "settings.timeFormat",
        descriptionKey: "settings.timeFormatDesc",
        icon: Clock,
        stateKey: "timeFormat",
        settingsKey: "timeFormat",
        options: TIME_FORMAT_OPTIONS,
      },
    ],
  },
  {
    id: "privacySecurity",
    titleKey: "settings.sections.privacySecurity",
    icon: Shield,
    items: [
      {
        id: "profileVisibility",
        type: "select",
        labelKey: "settings.profileVisibility",
        descriptionKey: "settings.profileVisibilityDesc",
        icon: Eye,
        stateKey: "profileVisibility",
        settingsKey: "profileVisibility",
        options: PROFILE_VISIBILITY_OPTIONS,
      },
      {
        id: "maskSensitiveData",
        type: "switch",
        labelKey: "settings.maskSensitiveData",
        descriptionKey: "settings.maskSensitiveDataDesc",
        icon: Eye,
        stateKey: "maskSensitiveData",
        settingsKey: "maskSensitiveData",
      },
      {
        id: "twoFactorEnabled",
        type: "switch",
        labelKey: "settings.twoFactorAuth",
        descriptionKey: "settings.twoFactorAuthDesc",
        icon: ShieldCheck,
        stateKey: "twoFactorEnabled",
        settingsKey: "twoFactorEnabled",
      },
      {
        id: "configureMfa",
        type: "button",
        labelKey: "settings.mfaAuth",
        descriptionKey: "settings.mfaAuthDesc",
        icon: ShieldCheck,
        actionId: "configureMfa",
        buttonLabel: "Configure",
      },
      {
        id: "blockedUsers",
        type: "button",
        labelKey: "settings.blockedUsers",
        descriptionKey: "settings.blockedUsersDesc",
        icon: Ban,
        actionId: "blockedUsers",
        buttonLabel: "Manage",
      },
      {
        id: "autoLogout",
        type: "switch",
        labelKey: "settings.autoLogout",
        descriptionKey: "settings.autoLogoutDesc",
        icon: Timer,
        stateKey: "autoLogout",
        settingsKey: "autoLogout",
      },
    ],
  },
  {
    id: "dataStorage",
    titleKey: "settings.sections.dataStorage",
    icon: Database,
    items: [
      {
        id: "autoBackup",
        type: "switch",
        labelKey: "settings.autoBackup",
        descriptionKey: "settings.autoBackupDesc",
        icon: CloudUpload,
        stateKey: "autoBackup",
        settingsKey: "autoBackup",
      },
      {
        id: "backupFrequency",
        type: "select",
        labelKey: "settings.backupFrequency",
        descriptionKey: "settings.backupFrequencyDesc",
        icon: CalendarClock,
        stateKey: "backupFrequency",
        settingsKey: "backupFrequency",
        options: BACKUP_FREQUENCY_OPTIONS,
        dependsOn: "autoBackup",
      },
      {
        id: "cloudSync",
        type: "switch",
        labelKey: "settings.cloudSync",
        descriptionKey: "settings.cloudSyncDesc",
        icon: CloudUpload,
        stateKey: "cloudSync",
        settingsKey: "cloudSync",
      },
      {
        id: "viewStorage",
        type: "button",
        labelKey: "settings.storageUsage",
        descriptionKey: "settings.storageUsageDesc",
        icon: HardDrive,
        actionId: "viewStorage",
        buttonLabel: "View",
      },
      {
        id: "clearCache",
        type: "button",
        labelKey: "settings.clearCache",
        descriptionKey: "settings.clearCacheDesc",
        icon: Trash2,
        actionId: "clearCache",
        variant: "outline",
        buttonLabel: "Clear",
      },
    ],
  },
  {
    id: "smartFeatures",
    titleKey: "settings.sections.smartFeatures",
    icon: Brain,
    items: [
      {
        id: "autoCategorize",
        type: "switch",
        labelKey: "settings.autoCategorize",
        descriptionKey: "settings.autoCategorizeDesc",
        icon: Brain,
        stateKey: "autoCategorize",
        settingsKey: "autoCategorize",
      },
      {
        id: "smartBudgeting",
        type: "switch",
        labelKey: "settings.smartBudgeting",
        descriptionKey: "settings.smartBudgetingDesc",
        icon: TrendingUp,
        stateKey: "smartBudgeting",
        settingsKey: "smartBudgeting",
      },
      {
        id: "scheduledReports",
        type: "select",
        labelKey: "settings.scheduledReports",
        descriptionKey: "settings.scheduledReportsDesc",
        icon: CalendarClock,
        stateKey: "scheduledReports",
        settingsKey: "scheduledReports",
        options: REPORT_SCHEDULE_OPTIONS,
      },
      {
        id: "expenseReminders",
        type: "switch",
        labelKey: "settings.expenseReminders",
        descriptionKey: "settings.expenseRemindersDesc",
        icon: Bell,
        stateKey: "expenseReminders",
        settingsKey: "expenseReminders",
      },
      {
        id: "predictiveAnalytics",
        type: "switch",
        labelKey: "settings.predictiveAnalytics",
        descriptionKey: "settings.predictiveAnalyticsDesc",
        icon: BarChart3,
        stateKey: "predictiveAnalytics",
        settingsKey: "predictiveAnalytics",
      },
    ],
  },
  {
    id: "accessibility",
    titleKey: "settings.sections.accessibility",
    icon: Accessibility,
    items: [
      {
        id: "screenReaderSupport",
        type: "switch",
        labelKey: "settings.screenReaderSupport",
        descriptionKey: "settings.screenReaderSupportDesc",
        icon: Accessibility,
        stateKey: "screenReaderSupport",
        settingsKey: "screenReaderSupport",
      },
      {
        id: "keyboardShortcuts",
        type: "switch",
        labelKey: "settings.keyboardShortcuts",
        descriptionKey: "settings.keyboardShortcutsDesc",
        icon: Keyboard,
        stateKey: "keyboardShortcuts",
        settingsKey: "keyboardShortcuts",
      },
      {
        id: "showShortcutIndicators",
        type: "switch",
        labelKey: "settings.showShortcutIndicators",
        descriptionKey: "settings.showShortcutIndicatorsDesc",
        icon: MonitorSmartphone,
        stateKey: "showShortcutIndicators",
        settingsKey: "showShortcutIndicators",
        dependsOn: "keyboardShortcuts",
      },
      {
        id: "reduceMotion",
        type: "switch",
        labelKey: "settings.reduceMotion",
        descriptionKey: "settings.reduceMotionDesc",
        icon: Minimize2,
        stateKey: "reduceMotion",
        settingsKey: "reduceMotion",
      },
      {
        id: "enhancedFocusIndicators",
        type: "switch",
        labelKey: "settings.enhancedFocusIndicators",
        descriptionKey: "settings.enhancedFocusIndicatorsDesc",
        icon: Focus,
        stateKey: "enhancedFocusIndicators",
        settingsKey: "enhancedFocusIndicators",
      },
      {
        id: "shortcutsGuide",
        type: "button",
        labelKey: "settings.shortcutsGuide",
        descriptionKey: "settings.shortcutsGuideDesc",
        icon: Keyboard,
        actionId: "shortcutsGuide",
        buttonLabel: "View",
      },
    ],
  },
  {
    id: "account",
    titleKey: "settings.sections.account",
    icon: User,
    items: [
      {
        id: "notificationSettings",
        type: "navigation",
        labelKey: "settings.notificationSettings",
        descriptionKey: "settings.notificationSettingsDesc",
        icon: Bell,
        actionId: "notificationSettings",
      },
      {
        id: "editProfile",
        type: "button",
        labelKey: "settings.editProfile",
        descriptionKey: "settings.editProfileDesc",
        icon: User,
        actionId: "editProfile",
        buttonLabel: "Edit",
      },
      {
        id: "changePassword",
        type: "button",
        labelKey: "settings.changePassword",
        descriptionKey: "settings.changePasswordDesc",
        icon: KeyRound,
        actionId: "changePassword",
        buttonLabel: "Change",
      },
      {
        id: "dataExport",
        type: "button",
        labelKey: "settings.dataExport",
        descriptionKey: "settings.dataExportDesc",
        icon: Download,
        actionId: "dataExport",
        buttonLabel: "Export",
      },
      {
        id: "deleteAccount",
        type: "button",
        labelKey: "settings.deleteAccount",
        descriptionKey: "settings.deleteAccountDesc",
        icon: AlertTriangle,
        actionId: "deleteAccount",
        variant: "destructive",
        buttonLabel: "Delete",
      },
    ],
  },
  {
    id: "helpSupport",
    titleKey: "settings.sections.helpSupport",
    icon: HelpCircle,
    items: [
      {
        id: "restartTour",
        type: "button",
        labelKey: "settings.restartTour",
        descriptionKey: "settings.restartTourDesc",
        icon: RotateCcw,
        actionId: "restartTour",
        buttonLabel: "Restart",
      },
      {
        id: "helpCenter",
        type: "navigation",
        labelKey: "settings.helpCenter",
        descriptionKey: "settings.helpCenterDesc",
        icon: HelpCircle,
        actionId: "helpCenter",
      },
      {
        id: "contactSupport",
        type: "navigation",
        labelKey: "settings.contactSupport",
        descriptionKey: "settings.contactSupportDesc",
        icon: MessageCircle,
        actionId: "contactSupport",
      },
      {
        id: "termsOfService",
        type: "navigation",
        labelKey: "settings.termsOfService",
        descriptionKey: "settings.termsOfServiceDesc",
        icon: FileText,
        actionId: "termsOfService",
      },
      {
        id: "privacyPolicy",
        type: "navigation",
        labelKey: "settings.privacyPolicy",
        descriptionKey: "settings.privacyPolicyDesc",
        icon: ShieldQuestion,
        actionId: "privacyPolicy",
      },
    ],
  },
  {
    id: "about",
    titleKey: "settings.sections.about",
    icon: Info,
    items: [],
    isInfoSection: true,
  },
];
