apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user_service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
          env:
            - name: DB_HOST
              value: "mysql" # MySQL service name inside k8s
            - name: DB_NAME
              value: "expense_user_service"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "123456"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server-svc:8761/eureka"
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service
  ports:
    - protocol: "TCP"
      port: 6001
      targetPort: 6001
  type: NodePort
