services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: expense_user_service
      # add MYSQL_USER and MYSQL_PASSWORD if you use other users
    networks:
      - springboot-net

  user_serive:
    image: user_serive:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expense_user_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - springboot-net
    ports:
      - "6001:6001"

networks:
  springboot-net:
    driver: bridge
