AUTOMATION_ENGINE=selenium
TEST_ENV=local
BASE_URL=http://localhost:3000
API_BASE_URL=http://localhost:8080
BASE_URL_LOCAL=http://localhost:3000
BASE_URL_QA=
BASE_URL_STAGE=
BASE_URL_PROD=
API_BASE_URL_LOCAL=http://localhost:8080
API_BASE_URL_QA=
API_BASE_URL_STAGE=
API_BASE_URL_PROD=
BROWSER=chrome
HEADLESS=true
EXPLICIT_WAIT_SEC=15
RETRY_COUNT=0
RERUN_FAILED_COUNT=0
TEST_USERNAME=
TEST_PASSWORD=
OTP_PROVIDER=
MFA_PROVIDER=
AUTOMATION_RUN_ID=
ARTIFACTS_ROOT=target/artifacts
CAPTURE_SCREENSHOT_ALWAYS=false
RECORD_VIDEO=false
RECORD_TRACE=false
DATA_WORKBOOK_PATH=
DATA_SHEET=default
DATA_ITERATION=0
DATA_PARTITION_INDEX=0
DATA_PARTITIONS=1
APP_START_CMD=
APP_STOP_CMD=
APP_WORKDIR=
APP_READY_URL=
APP_READY_TIMEOUT_SEC=180
cucumber.features=
cucumber.filter.tags=@smoke
cucumber.thread.count=1
