// Action types for chat
export const SEND_GROUP_CHAT = "SEND_GROUP_CHAT";
export const SEND_GROUP_CHAT_SUCCESS = "SEND_GROUP_CHAT_SUCCESS";
export const SEND_GROUP_CHAT_FAILURE = "SEND_GROUP_CHAT_FAILURE";

export const FETCH_GROUP_CHAT = "FETCH_GROUP_CHAT";
export const FETCH_GROUP_CHAT_SUCCESS = "FETCH_GROUP_CHAT_SUCCESS";
export const FETCH_GROUP_CHAT_FAILURE = "FETCH_GROUP_CHAT_FAILURE";

export const FETCH_GROUP_CHAT_HISTORY = "FETCH_GROUP_CHAT_HISTORY";
export const FETCH_GROUP_CHAT_HISTORY_SUCCESS =
  "FETCH_GROUP_CHAT_HISTORY_SUCCESS";
export const FETCH_GROUP_CHAT_HISTORY_FAILURE =
  "FETCH_GROUP_CHAT_HISTORY_FAILURE";

export const DELETE_CHAT_MESSAGE = "DELETE_CHAT_MESSAGE";
export const DELETE_CHAT_MESSAGE_SUCCESS = "DELETE_CHAT_MESSAGE_SUCCESS";
export const DELETE_CHAT_MESSAGE_FAILURE = "DELETE_CHAT_MESSAGE_FAILURE";

export const EDIT_CHAT_MESSAGE = "EDIT_CHAT_MESSAGE";
export const EDIT_CHAT_MESSAGE_SUCCESS = "EDIT_CHAT_MESSAGE_SUCCESS";
export const EDIT_CHAT_MESSAGE_FAILURE = "EDIT_CHAT_MESSAGE_FAILURE";

export const BULK_DELETE_CHAT_MESSAGES = "BULK_DELETE_CHAT_MESSAGES";
export const BULK_DELETE_CHAT_MESSAGES_SUCCESS =
  "BULK_DELETE_CHAT_MESSAGES_SUCCESS";
export const BULK_DELETE_CHAT_MESSAGES_FAILURE =
  "BULK_DELETE_CHAT_MESSAGES_FAILURE";

export const FETCH_UNREAD_GROUP_CHAT = "FETCH_UNREAD_GROUP_CHAT";
export const FETCH_UNREAD_GROUP_CHAT_SUCCESS =
  "FETCH_UNREAD_GROUP_CHAT_SUCCESS";
export const FETCH_UNREAD_GROUP_CHAT_FAILURE =
  "FETCH_UNREAD_GROUP_CHAT_FAILURE";

// Reply to a chat message
export const REPLY_CHAT = "REPLY_CHAT";
export const REPLY_CHAT_SUCCESS = "REPLY_CHAT_SUCCESS";
export const REPLY_CHAT_FAILURE = "REPLY_CHAT_FAILURE";

export const FETCH_CONVERSATIONS_LIST = "FETCH_CONVERSATIONS_LIST";
export const FETCH_CONVERSATIONS_LIST_SUCCESS =
  "FETCH_CONVERSATIONS_LIST_SUCCESS";
export const FETCH_CONVERSATIONS_LIST_FAILURE =
  "FETCH_CONVERSATIONS_LIST_FAILURE";

export const FETCH_ONE_TO_ONE_CHAT = "FETCH_ONE_TO_ONE_CHAT";
export const FETCH_ONE_TO_ONE_CHAT_SUCCESS = "FETCH_ONE_TO_ONE_CHAT_SUCCESS";
export const FETCH_ONE_TO_ONE_CHAT_FAILURE = "FETCH_ONE_TO_ONE_CHAT_FAILURE";

export const SEND_ONE_TO_ONE_MESSAGE = "SEND_ONE_TO_ONE_MESSAGE";
export const SEND_ONE_TO_ONE_MESSAGE_SUCCESS =
  "SEND_ONE_TO_ONE_MESSAGE_SUCCESS";
export const SEND_ONE_TO_ONE_MESSAGE_FAILURE =
  "SEND_ONE_TO_ONE_MESSAGE_FAILURE";

export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const RECEIVE_ONE_TO_ONE_MESSAGE = "RECEIVE_ONE_TO_ONE_MESSAGE";

export const SET_ACTIVE_CONVERSATION = "SET_ACTIVE_CONVERSATION";
export const CLEAR_ACTIVE_CONVERSATION = "CLEAR_ACTIVE_CONVERSATION";

export const UPDATE_TYPING_STATUS = "UPDATE_TYPING_STATUS";
export const CLEAR_TYPING_STATUS = "CLEAR_TYPING_STATUS";

export const UPDATE_ONLINE_STATUS = "UPDATE_ONLINE_STATUS";
export const UPDATE_ONLINE_STATUS_BATCH = "UPDATE_ONLINE_STATUS_BATCH";

export const ADD_REACTION = "ADD_REACTION";
export const ADD_REACTION_SUCCESS = "ADD_REACTION_SUCCESS";
export const ADD_REACTION_FAILURE = "ADD_REACTION_FAILURE";

export const REMOVE_REACTION = "REMOVE_REACTION";
export const REMOVE_REACTION_SUCCESS = "REMOVE_REACTION_SUCCESS";
export const REMOVE_REACTION_FAILURE = "REMOVE_REACTION_FAILURE";

export const UPDATE_MESSAGE_REACTION = "UPDATE_MESSAGE_REACTION";

export const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";
export const MARK_MESSAGES_READ_SUCCESS = "MARK_MESSAGES_READ_SUCCESS";

export const UPDATE_READ_RECEIPT = "UPDATE_READ_RECEIPT";

export const FETCH_FRIENDS_PRESENCE = "FETCH_FRIENDS_PRESENCE";
export const FETCH_FRIENDS_PRESENCE_SUCCESS = "FETCH_FRIENDS_PRESENCE_SUCCESS";
export const FETCH_FRIENDS_PRESENCE_FAILURE = "FETCH_FRIENDS_PRESENCE_FAILURE";

export const UPDATE_LAST_SEEN = "UPDATE_LAST_SEEN";

export const UPDATE_CONVERSATION_LAST_MESSAGE =
  "UPDATE_CONVERSATION_LAST_MESSAGE";
export const INCREMENT_UNREAD_COUNT = "INCREMENT_UNREAD_COUNT";
export const RESET_UNREAD_COUNT = "RESET_UNREAD_COUNT";

export const SET_WEBSOCKET_CONNECTED = "SET_WEBSOCKET_CONNECTED";
export const SET_WEBSOCKET_DISCONNECTED = "SET_WEBSOCKET_DISCONNECTED";
