sonar.projectKey=expenses-service
sonar.projectName=expenses-service
sonar.projectVersion=0.0.1
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.host.url=http://localhost:9001
