server:
  port: 8080
  address: 0.0.0.0



spring:
  application:
    name: EXPENSE-TRACKING-SYSTEM
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    allow-bean-definition-overriding: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false

  datasource:
    url: jdbc:mysql://localhost:5000/expense_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: jjayaprakash2002@gmail.com
    password: pgge ffhr txqm sxny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval: 5s
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      retries: 3
#      batch-size: 16384
#      linger-ms: 1
#      buffer-memory: 33554432
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: expense-tracking-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 1000