apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: expense
data:
  application-k8s.yaml: |
    server:
      port: 8080
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          probes:
            enabled: true
          show-details: never
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
    spring:
      jpa:
        hibernate:
          ddl-auto: update
        open-in-view: false
