// Friend suggestions
export const FETCH_FRIEND_SUGGESTIONS_REQUEST =
  "FETCH_FRIEND_SUGGESTIONS_REQUEST";
export const FETCH_FRIEND_SUGGESTIONS_SUCCESS =
  "FETCH_FRIEND_SUGGESTIONS_SUCCESS";
export const FETCH_FRIEND_SUGGESTIONS_FAILURE =
  "FETCH_FRIEND_SUGGESTIONS_FAILURE";

// Send friend request
export const SEND_FRIEND_REQUEST_REQUEST = "SEND_FRIEND_REQUEST_REQUEST";
export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS";
export const SEND_FRIEND_REQUEST_FAILURE = "SEND_FRIEND_REQUEST_FAILURE";

// Get friend requests
export const FETCH_FRIEND_REQUESTS_REQUEST = "FETCH_FRIEND_REQUESTS_REQUEST";
export const FETCH_FRIEND_REQUESTS_SUCCESS = "FETCH_FRIEND_REQUESTS_SUCCESS";
export const FETCH_FRIEND_REQUESTS_FAILURE = "FETCH_FRIEND_REQUESTS_FAILURE";

// Accept/reject friend request
export const RESPOND_TO_FRIEND_REQUEST_REQUEST =
  "RESPOND_TO_FRIEND_REQUEST_REQUEST";
export const RESPOND_TO_FRIEND_REQUEST_SUCCESS =
  "RESPOND_TO_FRIEND_REQUEST_SUCCESS";
export const RESPOND_TO_FRIEND_REQUEST_FAILURE =
  "RESPOND_TO_FRIEND_REQUEST_FAILURE";

// Add this new action type
export const ADD_NEW_FRIEND_REQUEST = "ADD_NEW_FRIEND_REQUEST";

// Remove friend request
export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";

export const FETCH_FRIENDS_REQUEST = "FETCH_FRIENDS_REQUEST";
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_FRIENDS_FAILURE = "FETCH_FRIENDS_FAILURE";

export const SET_ACCESS_LEVEL_REQUEST = "SET_ACCESS_LEVEL_REQUEST";
export const SET_ACCESS_LEVEL_SUCCESS = "SET_ACCESS_LEVEL_SUCCESS";
export const SET_ACCESS_LEVEL_FAILURE = "SET_ACCESS_LEVEL_FAILURE";

export const FETCH_I_SHARED_WITH_REQUEST = "FETCH_I_SHARED_WITH_REQUEST";
export const FETCH_I_SHARED_WITH_SUCCESS = "FETCH_I_SHARED_WITH_SUCCESS";
export const FETCH_I_SHARED_WITH_FAILURE = "FETCH_I_SHARED_WITH_FAILURE";

export const FETCH_SHARED_WITH_ME_REQUEST = "FETCH_SHARED_WITH_ME_REQUEST";
export const FETCH_SHARED_WITH_ME_SUCCESS = "FETCH_SHARED_WITH_ME_SUCCESS";
export const FETCH_SHARED_WITH_ME_FAILURE = "FETCH_SHARED_WITH_ME_FAILURE";

export const FETCH_FRIENDS_EXPENSES_SUCCESS = "FETCH_FRIENDS_EXPENSES_SUCCESS";
export const FETCH_FRIENDS_EXPENSES_FAILURE = "FETCH_FRIENDS_EXPENSES_FAILURE";

export const FETCH_FRIENDSHIP_SUCCESS = "FETCH_FRIENDSHIP_SUCCESS";
export const FETCH_FRIENDSHIP_FAILURE = "FETCH_FRIENDSHIP_FAILURE";

// Cancel friend request
export const CANCEL_FRIEND_REQUEST_REQUEST = "CANCEL_FRIEND_REQUEST_REQUEST";
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS";
export const CANCEL_FRIEND_REQUEST_FAILURE = "CANCEL_FRIEND_REQUEST_FAILURE";

// Remove friendship
export const REMOVE_FRIENDSHIP_REQUEST = "REMOVE_FRIENDSHIP_REQUEST";
export const REMOVE_FRIENDSHIP_SUCCESS = "REMOVE_FRIENDSHIP_SUCCESS";
export const REMOVE_FRIENDSHIP_FAILURE = "REMOVE_FRIENDSHIP_FAILURE";

// Block user
export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAILURE = "BLOCK_USER_FAILURE";

// Unblock user
export const UNBLOCK_USER_REQUEST = "UNBLOCK_USER_REQUEST";
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS";
export const UNBLOCK_USER_FAILURE = "UNBLOCK_USER_FAILURE";

// Get blocked users
export const FETCH_BLOCKED_USERS_REQUEST = "FETCH_BLOCKED_USERS_REQUEST";
export const FETCH_BLOCKED_USERS_SUCCESS = "FETCH_BLOCKED_USERS_SUCCESS";
export const FETCH_BLOCKED_USERS_FAILURE = "FETCH_BLOCKED_USERS_FAILURE";

// Get friendship stats
export const FETCH_FRIENDSHIP_STATS_REQUEST = "FETCH_FRIENDSHIP_STATS_REQUEST";
export const FETCH_FRIENDSHIP_STATS_SUCCESS = "FETCH_FRIENDSHIP_STATS_SUCCESS";
export const FETCH_FRIENDSHIP_STATS_FAILURE = "FETCH_FRIENDSHIP_STATS_FAILURE";

// Get mutual friends
export const FETCH_MUTUAL_FRIENDS_REQUEST = "FETCH_MUTUAL_FRIENDS_REQUEST";
export const FETCH_MUTUAL_FRIENDS_SUCCESS = "FETCH_MUTUAL_FRIENDS_SUCCESS";
export const FETCH_MUTUAL_FRIENDS_FAILURE = "FETCH_MUTUAL_FRIENDS_FAILURE";

// Search friends
export const SEARCH_FRIENDS_REQUEST = "SEARCH_FRIENDS_REQUEST";
export const SEARCH_FRIENDS_SUCCESS = "SEARCH_FRIENDS_SUCCESS";
export const SEARCH_FRIENDS_FAILURE = "SEARCH_FRIENDS_FAILURE";

// Get outgoing requests
export const FETCH_OUTGOING_REQUESTS_REQUEST =
  "FETCH_OUTGOING_REQUESTS_REQUEST";
export const FETCH_OUTGOING_REQUESTS_SUCCESS =
  "FETCH_OUTGOING_REQUESTS_SUCCESS";
export const FETCH_OUTGOING_REQUESTS_FAILURE =
  "FETCH_OUTGOING_REQUESTS_FAILURE";

// Get expense sharing summary
export const FETCH_EXPENSE_SHARING_SUMMARY_REQUEST =
  "FETCH_EXPENSE_SHARING_SUMMARY_REQUEST";
export const FETCH_EXPENSE_SHARING_SUMMARY_SUCCESS =
  "FETCH_EXPENSE_SHARING_SUMMARY_SUCCESS";
export const FETCH_EXPENSE_SHARING_SUMMARY_FAILURE =
  "FETCH_EXPENSE_SHARING_SUMMARY_FAILURE";

// Quick share expenses
export const QUICK_SHARE_EXPENSES_REQUEST = "QUICK_SHARE_EXPENSES_REQUEST";
export const QUICK_SHARE_EXPENSES_SUCCESS = "QUICK_SHARE_EXPENSES_SUCCESS";
export const QUICK_SHARE_EXPENSES_FAILURE = "QUICK_SHARE_EXPENSES_FAILURE";

// Batch share expenses
export const BATCH_SHARE_EXPENSES_REQUEST = "BATCH_SHARE_EXPENSES_REQUEST";
export const BATCH_SHARE_EXPENSES_SUCCESS = "BATCH_SHARE_EXPENSES_SUCCESS";
export const BATCH_SHARE_EXPENSES_FAILURE = "BATCH_SHARE_EXPENSES_FAILURE";

// Get recommended to share
export const FETCH_RECOMMENDED_TO_SHARE_REQUEST =
  "FETCH_RECOMMENDED_TO_SHARE_REQUEST";
export const FETCH_RECOMMENDED_TO_SHARE_SUCCESS =
  "FETCH_RECOMMENDED_TO_SHARE_SUCCESS";
export const FETCH_RECOMMENDED_TO_SHARE_FAILURE =
  "FETCH_RECOMMENDED_TO_SHARE_FAILURE";

// Friendship Report
export const FETCH_FRIENDSHIP_REPORT_REQUEST =
  "FETCH_FRIENDSHIP_REPORT_REQUEST";
export const FETCH_FRIENDSHIP_REPORT_SUCCESS =
  "FETCH_FRIENDSHIP_REPORT_SUCCESS";
export const FETCH_FRIENDSHIP_REPORT_FAILURE =
  "FETCH_FRIENDSHIP_REPORT_FAILURE";
export const CLEAR_FRIENDSHIP_REPORT = "CLEAR_FRIENDSHIP_REPORT";
