apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.job.name }}-automation-configuration
  labels:
    app.kubernetes.io/name: {{ .Values.job.name }}
data:
  AutomationConfiguration.yaml: {{ (tpl (.Files.Get "resources/AutomationConfiguration.yaml") .) | quote }}
