apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.job.name }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.job.name }}
data:
  automation-runner.properties: |
    RUN_MODE={{ .Values.runner.runMode }}
    AUTOMATION_RUNNER={{ .Values.runner.runnerType }}
    AUTOMATION_SUITE={{ .Values.runner.suite }}
    CUCUMBER_FILTER_TAGS={{ .Values.runner.tags }}
    TEST_ENV={{ .Values.runner.testEnv }}
    AUTOMATION_ENGINE={{ .Values.runner.engine }}
    RERUN_FAILURES={{ .Values.runner.rerunFailures }}
    FEATURES_PATH={{ .Values.runner.featuresPath }}
    ADDITIONAL_MAVEN_ARGS={{ .Values.runner.additionalMavenArgs }}
    BASE_URL={{ .Values.automation.baseUrl }}
    API_BASE_URL={{ .Values.automation.apiBaseUrl }}
    BROWSER={{ .Values.automation.browser.type }}
    HEADLESS={{ .Values.automation.browser.headless }}
    EXPLICIT_WAIT_SEC={{ .Values.automation.browser.explicitWaitSec }}
    REUSE_BROWSER_SESSION={{ .Values.automation.browser.reuseBrowserSession }}
    HTTP_CONNECT_TIMEOUT_SEC={{ .Values.automation.httpClient.connectTimeoutSec }}
    HTTP_READ_TIMEOUT_SEC={{ .Values.automation.httpClient.readTimeoutSec }}
    HTTP_WRITE_TIMEOUT_SEC={{ .Values.automation.httpClient.writeTimeoutSec }}
    HTTP_CONNECTION_POOL_SIZE={{ .Values.automation.httpClient.connectionPoolSize }}
    HTTP_SLEEP_TIMEOUT_MS={{ .Values.automation.httpClient.sleepTimeoutMs }}
    HTTP_MAX_RETRIES={{ .Values.automation.httpClient.maxRetries }}
    SSL_SKIP_CERTIFICATE_VALIDATION={{ .Values.automation.ssl.skipCertificateValidation }}
    RETRY_COUNT={{ .Values.automation.retry.retryCount }}
    RERUN_FAILED_COUNT={{ .Values.automation.retry.rerunFailedCount }}
    RETRY_API_MAX_ATTEMPTS={{ .Values.automation.retry.api.maxAttempts }}
    RETRY_API_INTERVAL_MS={{ .Values.automation.retry.api.intervalMs }}
    RETRY_API_BACKOFF_MULTIPLIER={{ .Values.automation.retry.api.backoffMultiplier }}
    RETRY_API_MAX_DELAY_MS={{ .Values.automation.retry.api.maxDelayMs }}
    RETRY_UI_POLL_MAX_ATTEMPTS={{ .Values.automation.retry.uiPoll.maxAttempts }}
    RETRY_UI_POLL_INTERVAL_MS={{ .Values.automation.retry.uiPoll.intervalMs }}
    RETRY_UI_POLL_BACKOFF_MULTIPLIER={{ .Values.automation.retry.uiPoll.backoffMultiplier }}
    RETRY_UI_POLL_MAX_DELAY_MS={{ .Values.automation.retry.uiPoll.maxDelayMs }}
    RECORD_VIDEO={{ .Values.automation.observability.recordVideo }}
    RECORD_TRACE={{ .Values.automation.observability.recordTrace }}
    CAPTURE_SCREENSHOT_ALWAYS={{ .Values.automation.observability.captureScreenshotAlways }}
    ARTIFACTS_ROOT={{ .Values.automation.artifacts.rootDirectory }}
