import { api } from "@/config/api";
import { safeApiCall } from "@/shared/utils/safeApiCall";

export const expenseApi = {
  getAll: (params) => safeApiCall(() => api.get("/api/expenses/fetch-expenses", { params })),
  getPaginated: (params) => safeApiCall(() => api.get("/api/expenses/fetch-expenses-paginated", { params })),
  getById: (id) => safeApiCall(() => api.get(`/api/expenses/expense/${id}`)),
  create: (data) => safeApiCall(() => api.post("/api/expenses/add-expense", data)),
  update: (id, data) => safeApiCall(() => api.put(`/api/expenses/edit-expense/${id}`, data)),
  delete: (id) => safeApiCall(() => api.delete(`/api/expenses/delete/${id}`)),
  getDailySpending: (params) => safeApiCall(() => api.get("/api/expenses/cashflow", { params })),
  getCashflow: (params) => safeApiCall(() => api.get("/api/expenses/cashflow", { params })),
  search: (query, params) => safeApiCall(() => api.get("/api/expenses/fetch-expenses", { params: { query, ...params } })),
  getByCategory: (categoryId, params) => safeApiCall(() => api.get(`/api/expenses/category/${categoryId}`, { params })),
  exportData: (params) => safeApiCall(() => api.get("/api/expenses/export", { params, responseType: "blob" })),
  getSuggestions: (data) => safeApiCall(() => api.post("/api/expenses/top-expense-names", data)),
  getGroupedByDate: (params) => safeApiCall(() => api.get("/api/expenses/groupedByDate", { params })),
  getSummary: (params) => safeApiCall(() => api.get("/api/expenses/summary-expenses", { params })),
  copy: (id) => safeApiCall(() => api.post(`/api/expenses/${id}/copy`)),
  editMultiple: (data) => safeApiCall(() => api.put("/api/expenses/edit-multiple", data)),
  deleteMultiple: (ids) => safeApiCall(() => api.delete("/api/expenses/delete-multiple", { data: ids })),
  getPrevious: (name, date) => safeApiCall(() => api.get(`/api/expenses/before/${name}/${date}`)),
  upload: (formData) => safeApiCall(() => api.post("/api/expenses/upload", formData, { headers: { "Content-Type": "multipart/form-data" } })),
  uploadCategories: (formData) => safeApiCall(() => api.post("/api/expenses/upload-categories", formData, { headers: { "Content-Type": "multipart/form-data" } })),
  createMultiple: (data) => safeApiCall(() => api.post("/api/expenses/add-multiple", data)),
  createMultipleTracked: (data) => safeApiCall(() => api.post("/api/expenses/add-multiple/tracked", data)),
  pollSaveProgress: (jobId) => safeApiCall(() => api.get(`/api/expenses/add-multiple/progress/${jobId}`)),
  getByDate: (params) => safeApiCall(() => api.get("/api/expenses/fetch-expenses-by-date", { params })),
  getByParticularDate: (params) => safeApiCall(() => api.get("/api/expenses/particular-date", { params })),
  getCategoriesDetailed: (params) => safeApiCall(() => api.get("/api/expenses/all-by-categories/detailed/filtered", { params })),
  getDetailed: (id) => safeApiCall(() => api.get(`/api/expenses/expense/${id}/detailed`)),
  getByPaymentMethod: (params) => safeApiCall(() => api.get("/api/expenses/all-by-payment-method/detailed/filtered", { params })),
};
