import { api } from "@/config/api";
import { safeApiCall } from "@/shared/utils/network/safeApiCall";

export const friendApi = {
  getAll: () => safeApiCall(() => api.get("/api/friendships/friends")),
  getDetailed: () => safeApiCall(() => api.get("/api/friendships/friends/detailed")),
  getSuggestions: () => safeApiCall(() => api.get("/api/friendships/suggestions")),
  sendRequest: (recipientId) => safeApiCall(() => api.post(`/api/friendships/request?recipientId=${recipientId}`)),
  getIncomingRequests: () => safeApiCall(() => api.get("/api/friendships/pending/incoming")),
  getOutgoingRequests: () => safeApiCall(() => api.get("/api/friendships/pending/outgoing")),
  getAllPending: () => safeApiCall(() => api.get("/api/friendships/pending")),
  respondToRequest: (id, accept) => safeApiCall(() => api.put(`/api/friendships/${id}/respond?accept=${accept}`)),
  cancelRequest: (id) => safeApiCall(() => api.delete(`/api/friendships/request/${id}/cancel`)),
  remove: (id) => safeApiCall(() => api.delete(`/api/friendships/${id}`)),
  setAccessLevel: (id, level) => safeApiCall(() => api.put(`/api/friendships/${id}/access?accessLevel=${level}`)),
  getISharedWith: () => safeApiCall(() => api.get("/api/friendships/i-shared-with")),
  getSharedWithMe: () => safeApiCall(() => api.get("/api/friendships/shared-with-me")),
  getFriendExpenses: (userId) => safeApiCall(() => api.get(`/api/expenses/user/${userId}`)),
  getDetails: (params) => safeApiCall(() => api.get("/api/friendships/details", { params })),
  getById: (id) => safeApiCall(() => api.get(`/api/friendships/${id}`)),
  block: (userId) => safeApiCall(() => api.post(`/api/friendships/block/${userId}`)),
  unblock: (userId) => safeApiCall(() => api.post(`/api/friendships/unblock/${userId}`)),
  getBlocked: () => safeApiCall(() => api.get("/api/friendships/blocked")),
  getStats: () => safeApiCall(() => api.get("/api/friendships/stats")),
  getMutualFriends: (userId) => safeApiCall(() => api.get(`/api/friendships/mutual/${userId}`)),
  search: (query) => safeApiCall(() => api.get(`/api/friendships/search?query=${query}`)),
  getSharingSummary: () => safeApiCall(() => api.get("/api/friendships/expense-sharing-summary")),
  quickShare: (userId, level) => safeApiCall(() => api.put(`/api/friendships/quick-share/${userId}?accessLevel=${level}`)),
  batchShare: (data) => safeApiCall(() => api.post("/api/friendships/batch-share", data)),
  getRecommendedToShare: () => safeApiCall(() => api.get("/api/friendships/recommended-to-share")),
  getReport: (params) => safeApiCall(() => api.get("/api/friendships/report", { params })),
  checkAreFriends: (u1, u2) => safeApiCall(() => api.get(`/api/friendships/are-friends/${u1}/${u2}`)),
  checkStatus: (userId) => safeApiCall(() => api.get(`/api/friendships/check/${userId}`)),
  checkExpenseAccess: (userId) => safeApiCall(() => api.get(`/api/friendships/access-check/${userId}`)),
};
