export const DASHBOARD_PIE_HEIGHT = 384;
export const DASHBOARD_PIE_INNER_RADIUS = 58;
export const DASHBOARD_PIE_OUTER_RADIUS = 108;
export const DASHBOARD_AREA_CHART_HEIGHT = 320;
export const DASHBOARD_COMPOSED_CHART_HEIGHT = 384;
export const DASHBOARD_BUDGET_RADIAL_HEIGHT = 228;
